template = "https://github.com/giellalt/template-lang-und"
rev_id = 135
template_sha = "ed843ac7e8774451e0cfca2edd3f0d5479f88e55"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
