template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "norw1262"
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
